### ISSUE TITLE
Intégrer les données du dépôt fridaylab dans le dépôt Etalab?

### ISSUE THREAD

**Issue by bzg** [etalab/fridaylab#2]
Je serais pour une page `fridaylab.md` avec la liste des fridaylabs passés et à venir.

L'idée est d'amener plus de gens à consulter (voire éditer) le dépôt `etalab`.

Ok pour toi @pachevalier ?

**Comment by pachevalier** [comment]
J'ai pas fait la mise à jour mais au départ l'idée c'était aussi d'ouvrir le fridaylab à d'autres administrations et de faire une mini offre de service sur "faire/tester/debugger un truc en une après midi". 

Si on fait ça ce serait logique de garder un repo à part. Sinon on fusionne.

**Comment by bzg** [comment]
Dans ce cas je suis pour qu'on garde ce dépôt `fridaylab`, nous en aurons l'usage du côté de sessions ouvertes sur l'appropriation des logiciels libres d'Etalab (udata, openfisca, etc.)

**Comment by bzg** [comment]
Du coup je me permets de fermer l'issue.
